const Images = {
	//登录
	loginBg: require('./loginBg.png'),
	loginBtn: require('./loginBtn.png'),
	loginInp: require('./loginInp.png'),
	bg: require('./bg.jpg'),
	//导航
	headerBg: require('./headerBg.png'),
	headerText: require('./headerText.png'),
	navTopBg: require('./navTopBg.png'),
	navTopCBg: require('./navTopCBg.png'),
	navTopSelect1: require('./navTopSelect1.png'),
	navTopSelect2: require('./navTopSelect2.png'),
	timeBg: require('./timeBg.png'),
	timeDown: require('./timeDown.png'),
	timeUp: require('./timeUp.png'),
	people: require('./people.png'),
	collect1: require('./collect1.png'),
	collect2: require('./collect2.png'),

	//首页
	homeBg: require('./homeBg.jpg'),
	homeLeft0: require('./homeLeft0.png'),
	homeLeft1: require('./homeLeft1.png'),
	homeLeft2: require('./homeLeft2.png'),
	homeLeftKuang: require('./homeLeftKuang.png'),
	homeNext: require('./homeNext.png'),
	homePrev: require('./homePrev.png'),
	more: require('./more.png'),
	homeSeparate: require('./homeSeparate.png'),
	homeStatistics: require('./homeStatistics.png'),
	homeEvent: require('./homeEvent.png'),
	homeEvent1: require('./homeEvent1.png'),
	homeBottom: require('./homeBottom.png'),
	homeBoard: require('./homeBoard.png'),
	homePen: require('./homePen.png'),
	homePositionG: require('./homePositionG.png'),
	homePositionR: require('./homePositionR.png'),
	homeBtnB: require('./homeBtnB.png'),
	homeBtnG: require('./homeBtnG.png'),
	homeClass: require('./homeClass.png'),
	playbackA: require('./playbackA.png'),
	playbackUn: require('./playbackUn.png'),
	return: require('./return.png'),
	eventBg: require('./eventBg.png'),
	eventClose: require('./eventClose.png'),
	eventSelect0: require('./eventSelect0.png'),
	eventSelect1: require('./eventSelect1.png'),
	videoPlay: require('./videoPlay.png'),
	//装备耗损统计页
	countryBtn0: require('./countryBtn0.png'),
	countryBtn1: require('./countryBtn1.png'),
	lossLeftBg: require('./lossLeftBg.png'),
	lossCenterBg: require('./lossCenterBg.png'),
	nationalflagE: require('./nationalflagE.png'),
	nationalflagW: require('./nationalflagW.png'),
	detailNameBg: require('./detailNameBg.png'),
	lossRightT: require('./lossRightT.png'),
	lossRightB: require('./lossRightB.png'),
	lossInfo: require('./lossInfo.png'),
	//部队页面
	unitSelect: require('./unitSelect.png'),
	unitSelectNo: require('./unitSelectNo.png'),
	unitBorder: require('./unitBorder.png'),
	unitLeft: require('./unitLeft.png'),
	unitLeftSelect: require('./unitLeftSelect.png'),
	unitLeftSelectNo: require('./unitLeftSelectNo.png'),
	unitLeftName: require('./unitLeftName.png'),
	unitTitle: require('./unitTitle.png'),
	unitGo: require('./unitGo.png'),
	unitNameK: require('./unitNameK.png'),
	unitCenterBg: require('./unitCenterBg.png'),
	unitLogo: require('./unitLogo.png'),
	militaryRank: require('./militaryRank.png'),
	divisionLevel1: require('./divisionLevel1.png'),
	divisionLevel2: require('./divisionLevel2.png'),
	unitEquipName: require('./unitEquipName.png'),
	unitDepartmentName: require('./unitDepartmentName.png'),
	unitCommanderBg: require('./unitCommanderBg.png'),
	commanderImgBg: require('./commanderImgBg.png'),
	commanderNameBg: require('./commanderNameBg.png'),
	people1: require('./people1.jpeg'),
	unitframe: require('./unitframe.png'),
	companyframe: require('./companyframe.png'),
	equipframe: require('./equipframe.png'),
	unitlogoBg: require('./unitlogoBg.png'),
	unitInfoBg: require('./unitInfoBg.png'),
	uniteventBg: require('./uniteventBg.png'),
	unitcasualties: require('./unitcasualties.png'),

	//装备页面
	equipClassify: require('./equipClassify.png'),
	equipClassifyS: require('./equipClassifyS.png'),
	equipBorder: require('./equipBorder.png'),
	equipLeftBg: require('./equipLeftBg.png'),
	equipNameBg: require('./equipNameBg.png'),
	equipNameBgH: require('./equipNameBgH.png'),
	equiplossframe: require('./equiplossframe.png'),
	eddeploy: require('./eddeploy.png'),
	edInfoBg: require('./edInfoBg.png'),
	edwastage: require('./edwastage.png'),
	edwastageC: require('./edwastageC.png'),
	ednamebg: require('./ednamebg.png'),
	edRightframe: require('./edRightframe.png'),
	economyframe1: require('./economyframe1.png'),
	economyframe2: require('./economyframe2.png'),
	economypeople1: require('./economypeople1.png'),
	economypeople2: require('./economypeople2.png'),
	economyprewar: require('./economyprewar.png'),
	foodpostwar: require('./foodpostwar.png'),
	foodprewar: require('./foodprewar.png'),
	economyOil1: require('./economyOil1.png'),
	economyOil2: require('./economyOil2.png'),
	militarymoney: require('./militarymoney.png'),
	militaryE0: require('./militaryE0.png'),
	militaryE1: require('./militaryE1.png'),
	militaryE2: require('./militaryE2.png'),
	militaryW0: require('./militaryW0.png'),
	militaryW1: require('./militaryW1.png'),
	militaryW2: require('./militaryW2.png'),
	militaryW3: require('./militaryW3.png'),
	conclusionH: require('./conclusionH.png'),
	conclusion: require('./conclusion.png'),

	economyC1: require('./economyC1.png'),
	economyC2: require('./economyC2.png'),
	economyC3: require('./economyC3.png'),
	economyC4: require('./economyC4.png'),
	economyLine: require('./economyLine.png'),
	foodPostwarBg: require('./foodPostwarBg.png'),
	foodPrewarBg: require('./foodPrewarBg.png'),

	collectBg: require('./collectBg.png'),
	collectA: require('./collectA.png'),
	collectNot: require('./collectNot.png'),
	collectSelect: require('./collectSelect.png'),
	collectSelectNot: require('./collectSelectNot.png'),
	collectExport: require('./collectExport.png'),

	locationgreen: require('./locationgreen.png'),
	locationred: require('./locationred.png'),
	tipbgimg: require('./tipbgimg.png'),
	tipcontent: require('./tipcontent.png'),
	circle: require('./circle.png'),
	tipbgimgGreen: require('./tipbgimgGreen.png'),
	tipcontentGreen: require('./tipcontentGreen.png'),
	circleGreen: require('./circleGreen.png'),
	homeDownYellow: require('./homeDownYellow.png'),
	homeDownGreen: require('./homeDownGreen.png'),
	homeUpGreen: require('./homeUpGreen.png'),
	homeUpYellow: require('./homeUpYellow.png'),
	closeRed: require('./closeRed.png'),
	fire: require('./fire.png'),
	tipbgimgRed: require('./tipbgimgRed.png'),
	tipcontentRed: require('./tipcontentRed.png'),
	homeDownRed: require('./homeDownRed.png'),
	homeUpRed: require('./homeUpRed.png'),

	bordermass: require('./bordermass.png'),

	people2: require('./people1.png'),
	people3: require('./people2.png'),
	people4: require('./people3.png'),
	pen: require('./pen.png'),
	imageNull: require('./imageNull.png'),
}
export default Images